- src/lib/auth.ts
- src/lib/paypay-rest-sdk.ts
This commit makes some minor language updates to code comments.
This is a fix for #11
> Updates to code comments

- src/lib/paypay-rest-sdk.ts
This updates the epoch value calculation to only consider value till seconds and not milliseconds
Fixes #21
> Updates epoch value to only consider seconds

- package.json
- tsconfig.json
This fixes the package load failure issue.
Solves #5
> Fix for incorrect main path in package.json

- package.json
- src/index.ts
- src/lib/auth.ts
- src/lib/conf.ts
- src/lib/constants.ts
- src/lib/paypay-rest-sdk.ts
Adds support for Account Link QR Code creation API
> Integrates Account Link QR Code creation API 

- package.json
- src/index.ts
- src/lib/auth.ts
- src/lib/httpsClient.ts
- src/lib/paypay-rest-sdk.ts
Fixes for auth and http header issues
JWT verification api added
> Fixes auth fixes, adds token verification api 

- .npmignore
- package-lock.json
- package.json
- tsconfig.json
This is a fix for the SDK NPM being incorrectly packaged.
Fixes #36
> Fix for NPM packaging

- package.json
- src/lib/paypay-rest-sdk.ts
As title. This arg was added recently and missing the description.
> Add merchant id JSdoc

- LICENSE
In #44 , @shreyanshp  mentioned that this source code belongs to PayPay. Therefore, I've added it to the copyright.
> Add paypay license

- src/index.ts
- src/lib/auth.ts
- src/lib/conf.ts
- src/lib/httpsClient.ts
- src/lib/paypay-rest-sdk.ts
We don't need to add this line because we specified here https://github.com/paypay/paypayopa-sdk-node/blob/be0ef47c0b2b0e95855c1e89be012a00cabd8237/tsconfig.json#L33.
> Remove no need "use strict"

- .github/pull_request_template.md
- src/README.md
Fix broken PR template links. Note: This PR already uses the updated template.
> Fix broken links

- .npmignore
- .npmrc
- SECURITY.md
1. npmrc can be omitted, as it only contains a default value.
2. remove other dispensable lines
> Remove npmrc

- src/lib/paypay-rest-sdk.ts
- test/paymentAuthCapture.test.ts
- test/paymentAuthRevert.test.ts
- test/paymentSubscription.test.ts
This PR adds units units for the SDK.
> Adds unit tests

- src/lib/paypay-rest-sdk.ts
> Fix for issue - "this.paypaySetupOptions is not a function"

- .travis.yml
- package.json
Fix for coveralls execution to calculate code coverage
> Fix for coveralls execution

- README.md
> add BCH badge

- .github/workflows/npm_publish.yml
- package.json
This PR has for goal to use github action to update the version number according to the tag when a release is created.
1. [NA] Does your submission pass tests?
2. [] Have you lint your code locally prior to submission?
> Using github action to update the version number according to the tag

- src/lib/conf.prod.json
- src/lib/conf.stage.json
- src/lib/conf.ts
- src/lib/httpsClient.ts
- src/lib/paypay-rest-sdk.ts
> Add Resolve URL builder and import refactoring

- src/lib/httpsClient.ts
> Optinoal chaining on status check from response payload

- .github/workflows/build-ci.yml
> Buildci update

- package-lock.json
- src/index.ts
- src/lib/conf.prod.json
- src/lib/conf.stage.json
- src/lib/paypay-rest-sdk.ts
- test/createPayment.test.ts
> Add API POST /v2/payments to create payment

- src/lib/conf.prod.json
- src/lib/conf.stage.json
- src/lib/paypay-rest-sdk.ts
> removed unused old v1 url

- README.md
> Add documentation for unlink api

- .github/workflows/build-ci.yml
> Workflow coverall fix

- src/index.ts
- src/lib/auth.ts
- src/lib/paypay-rest-sdk.ts
- test/PayPayRestSDK.test.ts
https://github.com/paypay/paypayopa-sdk-node/issues/188#issuecomment-794421323
> Enable to create the instance of PayPayRestSDK

- package-lock.json
- package.json
> Move nyc to devDependencies

- .github/workflows/build-ci-target.yml
- .github/workflows/build-ci.yml
> Fix cross workflow artifact downloads

- .github/workflows/build-ci-target.yml
> Specify -t lcov for cc-test-reporter after-build

- .github/workflows/build-ci-target.yml
> Use standard path to lcov.info

- .github/workflows/build-ci-target.yml
> Attempt to set GIT_COMMITTED_AT

- .github/workflows/build-ci-target.yml
> Fix missing uses

- .github/workflows/build-ci-target.yml
> Fix dollar sign typo

- .github/workflows/build-ci.yml
> Use coverallsapp github action instead of npm script

- .github/workflows/build-ci-target.yml
> CI: Update env variables for cc-test-reporter
